### ISSUE TITLE
Multiple animation snapping to end

### ISSUE THREAD

**Issue by Link2Twenty** [Dok11/easy-prop-animation#1]
Hi, when I have multiple animations with different durations all animations seem to snap to their final frame when the first duration is reached.

```js
EasyPropAnimation.run(scene.activeCamera, {
  position: [camera.x, camera.y, camera.z],
  target: [camTarget.x, camTarget.y, camTarget.z],
  transition: 'target 0.5s cubic-bezier(0.4, 0, 0.2, 1), position 1.5s cubic-bezier(0.4, 0, 0.2, 1)',
});
```

I've fixed this in a local version of your code by converting all animations to an animation group and then playing, and returning, that animation group at the end of the `run` functions. I'm happy to do a pull request if that's the route you want to take.

An added bonus of using animationGroup is you gain observables on the entire group like so

```js
console.log('animation start');

const anim = EasyPropAnimation.run(scene.activeCamera, {
  position: [camera.x, camera.y, camera.z],
  target: [camTarget.x, camTarget.y, camTarget.z],
  transition: 'target 0.5s cubic-bezier(0.4, 0, 0.2, 1), position 1.5s cubic-bezier(0.4, 0, 0.2, 1)',
});

anim.onAnimationGroupEndObservable.add(() => console.log('animation end'));
```

Thanks 😊

**Comment by Dok11** [comment]
Thanks for feedback.
I have fixed this bug locally via beginDirectAnimation, and will push updates in a day.

**Comment by Dok11** [comment]
> An added bonus of using animationGroup is you gain observables on the entire group like so

Intresting idea, I'll check this later, thank you!

**Comment by Dok11** [comment]
> An added bonus of using animationGroup is you gain observables on the entire group like so

Yes, I think it is a great idea, so, since 1.0.3 this library returns an AnimationGroup! 😃
