### ISSUE TITLE
Update Babylon Version

### ISSUE THREAD

**Issue by fluxxus** [Dok11/easy-prop-animation#3]
Is there any particular reason why Babylon v5 is listed as peer dependancy? From what I know, your library is working just fine with latest Babylon version(`6.27.1`), but I needed to import it manually without `npm`.

Both` --legacy-peer-deps` and `--force` is something I prefer to avoid if possible.

Thx

**Comment by Dok11** [comment]
Thanks for feedback. Updated!

**Comment by fluxxus** [comment]
Same thing with Babylon 7 :)

**Comment by Dok11** [comment]
Oops, I did it again..
Updated!
